# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HA4LCqPi_gmnXKACjkpfgXYeQQlZ8KVl
"""

from flask import Flask, request, jsonify
import numpy as np
import pickle

app = Flask(__name__)

# Load your model and scaler
model = pickle.load(open("model.pkl", "rb"))
scaler = pickle.load(open("scaler.pkl", "rb"))

@app.route("/")
def home():
    return "Diabetes Prediction API is running."

@app.route("/predict", methods=["POST"])
def predict():
    data = request.json

    # Convert input into array
    features = np.array([[
        data["Pregnancies"],
        data["Glucose"],
        data["BloodPressure"],
        data["SkinThickness"],
        data["Insulin"],
        data["BMI"],
        data["DiabetesPedigreeFunction"],
        data["Age"]
    ]])

    # Apply scaling
    scaled = scaler.transform(features)

    # Make prediction
    prediction = int(model.predict(scaled)[0])

    return jsonify({
        "prediction": prediction,
        "message": "Diabetic" if prediction == 1 else "Not Diabetic"
    })

if __name__ == "__main__":
    app.run()